web_server_quiz/web_server_quiz/web/forms/login_form.py
from wtforms import StringField, PasswordField, SubmitField, BooleanField, Form
from wtforms.validators import DataRequired


class IndexFormError(Exception):
    pass


class BaseForm(Form):
    """
    Base class reconfiguration in order to turn off nasty csrf tokens
    """

    class Meta:
        csrf = False


class LoginForm(BaseForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    sign_in_button = SubmitField('Sign In')

web_server_quiz/web_server_quiz/web/forms/registration_form.py
from wtforms import StringField, PasswordField, IntegerField, RadioField, Form, validators
from wtforms.fields.html5 import EmailField
from wtforms.widgets import html5


class IndexFormError(Exception):
    pass


class BaseForm(Form):
    """
    Base class reconfiguration in order to turn off nasty csrf tokens
    """

    class Meta:
        csrf = False


class RegistrationForm(BaseForm):
    username = StringField('Username', validators=[validators.required()])
    password = PasswordField('Password', validators=[validators.required()])
    repeat_password = PasswordField('Password', validators=[validators.required()])
    email = EmailField('e-mail', validators=[validators.required(), validators.Email()])
    gender = RadioField('gender', validators=[validators.required()], choices=[('male', 'Male'),
                                                                               ('female', 'Female')])
    age = IntegerField('Age', widget=html5.NumberInput(min="1", max="99"), validators=[validators.required()])
    religion = StringField('religion', validators=[validators.required()])

web_server_quiz/web_server_quiz/web/blueprints/frontend.py
import hashlib

from flask import render_template, flash, redirect, url_for, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.urls import url_parse

import web.forms as forms
from models import User, QuizQuestions

frontend = Blueprint('frontend', __name__)


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = forms.LoginForm(request.form)
    if form.validate():
        try:
            user = User.get(User.username == form.username.data)
            if user is None or user.password_hash != hashlib.sha256(form.password.data.encode('UTF-8')).hexdigest():
                flash('Invalid username or password')
                return redirect(url_for('frontend.login'))
            login_user(user)
            next_page = request.args.get('next')
            if not next_page or url_parse(next_page).netloc != '':
                next_page = url_for('frontend.index')
            return redirect(next_page)
        except User.DoesNotExist:
            flash('Invalid username or password')
            return redirect(url_for('frontend.login'))
    return render_template('login.html', title='Sign In', form=form)


@frontend.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('frontend.index'))


@frontend.route('/', methods=['GET', 'POST'])
@frontend.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = forms.IndexForm(request.form)
    return render_template('index.html', title='Server', form=form)


@frontend.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('frontend.index'))
    form = forms.RegistrationForm(request.form)
    if form.validate():
        try:
            User.add(username=form.username.data,
                     email=form.email.data,
                     password=form.password.data,
                     gender=form.gender.data,
                     age=form.age.data,
                     religion=form.religion.data)
            flash('Congratulations, you are now a registered user!')
            return redirect(url_for('frontend.login'))
        except Exception as err:
            flash(str(err), 'danger')
            return redirect(url_for('frontend.register'))
    return render_template('registration.html', title='Register', form=form)


@frontend.route('/quiz_creation', methods=['GET', 'POST'])
@login_required
def quiz_creation():
    return render_template('quiz_creation.html', title='Quiz creation')


@frontend.route('/logged_user', methods=['GET', 'POST'])
def logged_user():
    pass


@frontend.route('/quiz/<quiz_id>', methods=['GET', 'POST'])
@login_required
def quiz(quiz_id: int):
    quiz_list = [quiz_data for quiz_data in
                 QuizQuestions.select(QuizQuestions.question_text, Choices.id, Choices.choice_text).dicts().
                     join(Choices).group_by(Choices.choice_text, QuizQuestions.question_text, Choices.id).where(
                     QuizQuestions.quiz_id == quiz_id)]
    result_dict = {}
    for question in quiz_list:
        if question['question_text'] not in result_dict:
            result_dict[question['question_text']] = []
    for question in quiz_list:
        result_dict[question['question_text']].append({'text': question['choice_text'], 'id': question['id']})
    return render_template('quiz.html', title='Quiz', result_dict=result_dict)


@frontend.route('/user_profile/<username>', methods=['GET', 'POST'])
@login_required
def user_profile(username: str):
    user = User.get(User.username == username)
    return render_template('user_profile.html', title='User Profile', user=user)

web_server_quiz/web_server_quiz/web/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    {% block styles %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css"
              href="{{ url_for('static', filename='css/bootstrap/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/alertify/alertify.min.css') }}">
        <link rel="stylesheet" type="text/css"
              href="{{ url_for('static', filename='css/alertify/themes/bootstrap.css') }}">

    {% endblock %}

    <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}" type="image/x-icon">
    <title>Quiz Web Server</title>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light shadow-sm">
    <img src="../static/yadro_logo.png" width="50" height="50" class="d-inline-block align-top" alt="">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/quiz_creation">Create a new quiz</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-item nav-link"
                       href="{{ url_for('frontend.user_profile', username=current_user.username) }}">{{ current_user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-danger" href="{{ url_for('frontend.logout') }}">Logout</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block content %}

{% endblock %}

{% block scripts %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/jquery/jquery-3.4.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/alertify/alertify.js') }}"></script>
    <script type="text/javascript">
        function callSuccessAlertify(data) {
            let message = extractMessage(data);
            if (message !== null) {
                alertify.success(message, '60');
            }
        }

        function callFailureAlertify(data) {
            let message = extractMessage(data);
            if (message !== null) {
                alertify.error(message, '-1');
            }
        }

        function extractMessage(data) {
            if (data.hasOwnProperty('message')) {
                return data.message;
            } else {
                if (data.hasOwnProperty('responseJSON')) {
                    if (data.responseJSON.hasOwnProperty('message')) {
                        return data.responseJSON.message;
                    } else {
                        return null;
                    }
                } else {
                    return null;
                }
            }
        }
    </script>

{% endblock %}

</body>
</html>

web_server_quiz/web_server_quiz/web/templates/index.html
{%- extends "base.html" %}

{% block styles %}
    {{ super() }}

{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>

{% endblock %}

{% block content %}


    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="container">
                <div class=flashes>
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible text-center" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <div class="container py-5">
        Choose one of the quizzes below:
        <div id="quiz" class="container py-4">
            <div class="list-group" id="quiz_list">
            </div>
        </div>
    </div>

{% endblock %}

web_server_quiz/web_server_quiz/web/templates/login.html
{% extends "base.html" %}

{% block styles -%}
    {{ super() }}
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron" style="padding: 10px">
            <h2 align="center">Welcome to the Quiz Server!</h2>
        </div>
    </div>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="container">
                    <div class=flashes>
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible text-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endwith %}

        <form method="post" role="form" action="/login">
            <div class="form-group">
                <label for="username">Username</label>
                <div id="username">{{form.username(class_="form-control")}}</div>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <div id="password">{{form.password(class_="form-control")}}</div>
            </div>
            <div>
                <button type="submit" class="btn btn-success">Login</button>
            </div>
        </form>
        <h5 align="center"><p>New User? <a href="{{ url_for('frontend.register') }}">Click to Register!</a></p></h5>
    </div>
{% endblock %}

web_server_quiz/web_server_quiz/web/templates/quiz.html
{%- extends "base.html" %}

{% block styles %}
    {{ super() }}

{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/jqueryserializeJSON/jquery.serializeJSON.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/quiz.js') }}"></script>

{% endblock %}

{% block content %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="container">
                <div class=flashes>
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible text-center" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endwith %}

    <div class="container py-5">
        <div class="container">
        <form id="quiz_form" method="post" role="form" action="/quiz">
            <ul class="list-group">
                {% set count = namespace(value=0) %}
                {% for key, values in result_dict.items() %}
                    <p class="font-weight-light">
                        {{ key }}
                    </p>
                    {% for value in values %}
                        <li class="list-group-item"><input id="{{ value['id']  }}" name="{{ count.value }}"
                                                           required type="radio"
                                                           value="{{value['id'] }}">
                            <label for="{{ value['id'] }}">{{ value['text'] }}</label></li>
                    {% endfor %}
                    <br>
                    {% set count.value = count.value + 4 %}
                {% endfor %}
            </ul>
        </form>
        <button class="btn btn-success" onclick="sendData()">Get Result!</button>
        </div>
    </div>

{% endblock %}

web_server_quiz/web_server_quiz/web/templates/quiz_creation.html
{% extends "base.html" %}

{% block styles -%}
    {{ super() }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/jqueryserializeJSON/jquery.serializeJSON.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/quiz_create.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron" style="padding: 10px">
            <h2 align="center">Create quiz</h2>
        </div>
    </div>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="container">
                    <div class=flashes>
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible text-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endwith %}

        <form id="quiz_form" method="post" role="form" action="/quiz_creation">
            <div class="form-group">
                <label for="quiz_name">Quiz name</label>
                <input class="form-control" id="quiz_name" name="quiz_name" required type="text">
                <div class="valid-feedback" id="quiznameIsFree" style="display: none">
                    Name is available.
                </div>
                <div class="invalid-feedback" id="quiznameIsBusy" style="display: none">
                    Name is already in use.
                </div>
            </div>
            <div class="form-group">
                <label for="quiz_description">Quiz description</label>
                <input class="form-control" id="quiz_description" name="quiz_description" required type="text">
            </div>
            <div id="questions">
            </div>
        </form>
        </br>
        <div style="display:inline-block">
            <button class="btn btn-warning" onclick="addQuestion()">New Question</button>
            <button class="btn btn-success" onclick="sendData()">Create</button>
        </div>
    </div>
{% endblock %}

web_server_quiz/web_server_quiz/web/templates/registration.html
{% extends "base.html" %}

{% block styles -%}
{{ super() }}
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for('static', filename='js/registration.js') }}"></script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron" style="padding: 10px">
        <h2 align="center">Create your account</h2>
    </div>
</div>
<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="container">
        <div class=flashes>
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <!-- <strong>Title</strong> --> {{ message }}
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% endwith %}

    <form id="register_form" method="post" role="form" action="/register">
        <div class="form-group">
            <label for="username">Username</label>
            {{form.username(class_="form-control")}}
            <div class="valid-feedback" id="usernameIsFree" style="display: none">
                Username is available.
            </div>
            <div class="invalid-feedback" id="usernameIsBusy" style="display: none">
                Username is already in use.
            </div>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            {{form.password(class_="form-control")}}
        </div>
        <div class="form-group">
            <label for="repeat_password">Confirm password</label>
            {{form.repeat_password(class_="form-control")}}
            <div class="invalid-feedback" id="passwordsNotMatch" style="display: none">
                Passwords are not match!
            </div>
        </div>
        <div class="form-group">
            <label for="email">e-mail</label>
            {{form.email(class_="form-control")}}
            <div class="valid-feedback" id="emailIsFree" style="display: none">
                E-mail is available.
            </div>
            <div class="invalid-feedback" id="emailIsBusy" style="display: none">
                E-mail is already in use.
            </div>
        </div>
        <div class="form-group">
            <label for="gender">Gender</label>
            <div id="gender">
                {% for subfield in form.gender %}
                <tr>
                    <td>{{ subfield (required=True)}}</td>
                    <td>{{ subfield.label }}</td>
                </tr>
                <br/>
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <label for="age">Age</label>
            {{form.age(class_="form-control")}}
        </div>
        <div class="form-group">
            <label for="religion">Religion</label>
            {{form.religion(class_="form-control")}}
        </div>
            <button type="submit" class="btn btn-success">Register</button>
    </form>
</div>
{% endblock %}

web_server_quiz/web_server_quiz/web/templates/user_profile.html
{% extends "base.html" %}

{% block styles -%}
    {{ super() }}
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="container">
                    <div class=flashes>
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible text-center" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endwith %}


        <div class="container py-2">
            <h3>User: {{ user.username }}</h3>
        </div>
        <hr>
        <div class="container py-2">
            <ul class="list-group">
                <li class="list-group-item">Email: {{ user.email }}</li>
                <li class="list-group-item">Age: {{ user.age }}</li>
                <li class="list-group-item">Gender: {{ user.gender }}</li>
                <li class="list-group-item">Religion: {{ user.religion }}</li>
            </ul>
        </div>
    </div>
{% endblock %}